# Generated by Django 3.1.7 on 2021-05-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup_detail',
            old_name='Mobile_No',
            new_name='pin',
        ),
    ]
